name: bim_assist_test
description: BimAssist_test
version: 0.0.1+1
publish_to: 'none'


environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  # Widgets
  flutter_svg: ^2.0.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^3.0.1
  url_launcher: ^6.2.2

flutter_gen:
  output: lib/src/core/resources
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/



